services:
  - type: web
    name: flask-app
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - fromDatabase:
          name: DATABASE_URL
          property: connectionString
          databaseName: flask-db

databases:
  - name: flask-db
    plan: free


